version: '3.8'

services:
  postgres-auth:
    image: postgres:15-alpine
    container_name: auth-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - auth_pgdata:/var/lib/postgresql/data

  auth-service:
    build: .
    container_name: auth-app
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DOCKER_DB_HOST=postgres-auth
    depends_on:
      - postgres-auth

volumes:
  auth_pgdata: