spring.application.name=auth-service

# JPA & Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.enabled=true

# Security Settings
application.security.jwt.expiration-minutes=15
application.security.jwt.refresh-token.expiration-days=7
internal.api-key=${INTERNAL_API_KEY}
jwt.private-key=${JWT_PRIVATE_KEY}

server.port=${APP_PORT:8080}





logging.level.org.springframework.data.redis.core=DEBUG

logging.level.io.lettuce.core=DEBUG

logging.level.org.springframework.cache=TRACE
logging.level.org.springframework.data.redis.cache=TRACE


# Redis
spring.cache.type=redis