spring.datasource.url=jdbc:postgresql://${DOCKER_DB_HOST}:${DB_HOST_PORT:5432}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

application.config.user-url=${USER_SERVICE_DOCKER_URL}

# Redis
spring.data.redis.host=${DOCKER_REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}