spring.datasource.url=jdbc:postgresql://localhost:${DB_HOST_PORT:5432}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

application.config.user-url=${USER_SERVICE_URL}

logging.level.org.springframework.cache=TRACE
logging.level.org.springframework.data.redis.cache=TRACE

# Redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}